### ISSUE TITLE
Add {Bober}: {BoberErgo}

### ISSUE THREAD

**Issue by MavBg** [spectrum-finance/ergo-token-list#25]
- [x] I understand that token listing is not required to use the Spectrum Finance Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Spectrum Finance default token list.
- [x] I will not ping the Spectrum Finance team about this listing request.

## Please provide the following information for your token
Project Name:  BoberErgo
Token Address:  b0b312cde931c8bbdac0dac5bfd8e2c03bf4611275dc967988c8d15bd5ec20e0
Token Name:  Bober
Token Ticker:  Bober
Decimals:  3
Logo URI:  Uploaded to /token-logos

### Socials (optional)
Website URL (required):  not available yet
Twitter URL (required):  https://twitter.com/Bober_Ergo
Discord URL (required):  
Telegram URL (optional):  https://t.me/BoberErgo
CoinMarketCap URL (optional):  
CoinGecko URL (optional):

**Comment by yasha-black** [comment]
#28 merged
