### ISSUE TITLE
Add PEPERG: PEPERG

### ISSUE THREAD

**Issue by Hq3r** [spectrum-finance/ergo-token-list#3]
- [x] I understand that token listing is not required to use the Spectrum Finance Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Spectrum Finance default token list.
- [x] I will not ping the Spectrum Finance team about this listing request.

## Please provide the following information for your token
Project Name:  PepeErgo
Token Address: https://ergexplorer.com/token#91289d5cefb9d78e3ea248d4e9c5b0e3c3de54f64bfae85c0070580961995262 
Token Name:  PEPErg
Token Ticker:  PEPErg
Decimals:  0
Logo URI:  https://raw.githubusercontent.com/spectrum-finance/token-logos/89556e899a5012c8b94d0f6539a7e25ead4bf014/logos/ergo/91289d5cefb9d78e3ea248d4e9c5b0e3c3de54f64bfae85c0070580961995262.svg

### Socials (optional)
Website URL (required):  https://peperg.com/
Twitter URL (required):  https://twitter.com/pepeergo
Discord URL (required):  https://discord.gg/U8VT3qcj
Telegram URL (optional):  
CoinMarketCap URL (optional):  
CoinGecko URL (optional):

**Comment by Hq3r** [comment]
list peperg

**Comment by yasha-black** [comment]
Added #5
