### ISSUE TITLE
Add hodlERG3: hodlERG3

### ISSUE THREAD

**Issue by pulsarz** [spectrum-finance/ergo-token-list#4]
- [x] I understand that token listing is not required to use the Spectrum Finance Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Spectrum Finance default token list.
- [x] I will not ping the Spectrum Finance team about this listing request.

## Please provide the following information for your token
Project Name:  hodlERG 3%
Token Address:  cbd75cfe1a4f37f9a22eaee516300e36ea82017073036f07a09c1d2e10277cda
Token Name:  hodlERG3
Token Ticker:  hodlERG3
Decimals:  9
Logo URI:  https://media.discordapp.net/attachments/1138798943803809792/1139177368704008222/HODL-8-1.png

### Socials (optional)
Website URL (required):  https://phoenixfi.app/ or https://app.hodlcoin.co.in/
Twitter URL (required):  https://twitter.com/PhoenixErgo
Discord URL (required):  -
Telegram URL (optional):  
CoinMarketCap URL (optional):  
CoinGecko URL (optional):

**Comment by yasha-black** [comment]
added #5
