### ISSUE TITLE
Add RSN: Rosen Bridge

### ISSUE THREAD

**Issue by mhssamadani** [spectrum-finance/ergo-token-list#8]
- [x] I understand that token listing is not required to use the Spectrum Finance Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Spectrum Finance default token list.
- [x] I will not ping the Spectrum Finance team about this listing request.

## Please provide the following information for your token
Project Name:  Rosen Bridge
Token Address:  https://ergexplorer.com/token#8b08cdd5449a9592a9e79711d7d79249d7a03c535d17efaee83e216e80a44c4b
Token Name:  Rosen
Token Ticker:  RSN
Decimals:  3
Logo URI:  https://github.com/rosen-bridge/statics/blob/7307d12c0e594ed1a6fbda827d8827776d10fcf7/logorosentwitter.png

### Socials (optional)
Website URL (required):  https://rosen.tech/
Twitter URL (required):  https://twitter.com/RosenBridge_erg
Discord URL (required):  
Telegram URL (optional):  
CoinMarketCap URL (optional):  
CoinGecko URL (optional):

**Comment by yasha-black** [comment]
#9 Added
